sudo: false
language: scala
scala:
  - 2.11.7
addons:
  apt:
    packages:
      - libc6-i386
      - lib32z1
      - lib32stdc++6
before_install:
  - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar xf android-sdk_r24.4.1-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export ANDROID_SDK_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo yes | android update sdk --all --filter platform-tools --no-ui
  - echo yes | android update sdk --all --filter build-tools-24.0.1 --no-ui
  - echo yes | android update sdk --all --filter android-23 --no-ui
  - echo yes | android update sdk --all --filter extra-android-support --no-ui
  - echo yes | android update sdk --all --filter extra-android-m2repository --no-ui
  - echo yes | android update sdk --all --filter extra-google-m2repository --no-ui
  - openssl aes-256-cbc -K $encrypted_e4893f5c86d2_key -iv $encrypted_e4893f5c86d2_iv -in properties.tar.enc -out properties.tar -d
  - tar xvf properties.tar
  - mv local.properties modules/app/local.properties
  - export GIT_BRANCH=${TRAVIS_BRANCH}
  - export GIT_PR=${TRAVIS_PULL_REQUEST}
  - export GIT_COMMIT=${TRAVIS_COMMIT}
  - pip install --user codecov && codecov -t ${CODECOV_TOKEN}
script:
  - sbt ++$TRAVIS_SCALA_VERSION "project app" android:packageRelease
